language: rust
rust:
  - 1.3.0
  - stable
  - beta
  - nightly
sudo: false
script:
  - cargo build --verbose
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      travis_wait cargo test --verbose --features pattern;
    else
      travis_wait cargo test --verbose;
    fi
  - ./run-shootout-test
  - cargo doc --verbose
  - cargo test --verbose --manifest-path=regex-syntax/Cargo.toml
  - cargo doc --verbose --manifest-path=regex-syntax/Cargo.toml
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      travis_wait ./run-bench rust;
      travis_wait ./run-bench rust-bytes --no-run;
      travis_wait ./run-bench rust-plugin --no-run;
      travis_wait ./run-bench pcre --no-run;
      travis_wait ./run-bench onig --no-run;
      travis_wait cargo test --verbose --manifest-path=regex_macros/Cargo.toml;
    fi
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  [ $TRAVIS_RUST_VERSION = nightly ] &&
  echo '<meta http-equiv=refresh content=0;url=regex/index.html>' > target/doc/index.html &&
  pip install ghp-import --user $USER &&
  $HOME/.local/bin/ghp-import -n target/doc &&
  git push -qf https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages &&
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
    tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make && make install DESTDIR=../tmp && cd ../.. &&
  PATH="./kcov-master/tmp/usr/local/bin:$PATH" ./run-kcov --coveralls-id $TRAVIS_JOB_ID
env:
  global:
    secure: VvIrYRW/a8FmBA61hn1bDrqWwR92tANOT6PCeLYd9A9ViQrN07PE6uGsnd9iwr8itck10Ctl1mThZYUkK8BDFEmlvSxOFJ/Po5eRe6A1CYuFF40zizJ+3NllVkN20kwoQDe0kxwZVDGO9Yi1icHUrbRPWDfS+1tfobO/UT8Dlng=
notifications:
  email:
    on_success: never
