[package]
name = "regex-lite"
version = "0.1.6"  #:version
authors = ["The Rust Project Developers", "Andrew Gallant <jamslam@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang/regex/tree/master/regex-lite"
documentation = "https://docs.rs/regex-lite"
description = """
A lightweight regex engine that optimizes for binary size and compilation time.
"""
workspace = ".."
edition = "2021"
rust-version = "1.65"
autotests = false

# Features are documented in the "Crate features" section of the crate docs:
# https://docs.rs/regex-lite/*/#crate-features
#
# (Currently there are no supported features. 'std' is technically one, but it
# is currently required.)
[features]
default = ["std", "string"]
std = []
string = []

[dev-dependencies]
anyhow = "1.0.69"
regex-test = { path = "../regex-test", version = "0.1.0" }

[[test]]
path = "tests/lib.rs"
name = "integration"

[package.metadata.docs.rs]
# We want to document all features.
all-features = true
